version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: itransz1@ml
      MYSQL_DATABASE: itranszEsolutions
      MYSQL_PASSWORD: password
      MYSQL_USER: itransz
    volumes:
    - backup_data:/var/lib/mysql
  wordpress:
    image: wordpress:latest
    ports:
        - "8080:80"
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: itransz
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: itranszEsolutions
    volumes:
      - ./itransz-esolutions:/var/www/html
  
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./itransz-esolutions:/var/www/html  # Ensure NGINX serves files from the local volume
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wordpress

  
volumes:
    backup_data:

    